---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: secureblue-nvidia-open-hardened
# description will be included in the image's metadata
description: secureblue with GNOME, open NVIDIA and a few personal tweaks

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/silverblue-nvidia-open-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    source: ghcr.io/fromelicks/modules/dnf:latest
    repos:
      files:
        - gh-cli.repo
        - netbird.repo
        - terra.repo
      copr:
        enable:
          - name: wezfurlong/wezterm-nightly
            chroot: fedora-44-x86_64
    install:
      packages:
        - chezmoi
        - fish
        - foot
        - gamescope
        - gh
        - ghostty # repo: terra
        - git
        - golang
        - keepassxc
        - kitty
        - micro
        - rclone
        - syncthing
        - wezterm # repo: copr:copr.fedorainfracloud.org:wezfurlong:wezterm-nightly
        - xpra
        - zed # repo: terra
        # Fedora package installs to system extension path; EGO build is hard-coded to user paths
        - gnome-shell-extension-gsconnect
        - repo: terra
          packages:
            - terra-release
            - terra-gpg-keys
    # remove: # Example removal
    #   packages:
    #     - firefox
    #     - firefox-langpacks

  - type: script
    scripts:
      - install-netbird.sh

  - type: systemd
    system:
      enabled:
        - netbird.service
    user:
      enabled:
        - syncthing.service

  - type: gschema-overrides

  - type: gnome-extensions
    install:
      - 6099 # PaperWM

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: user
        # If no repo information is specified, Flathub will be used by default
        install:
          - org.gnome.Loupe
          - org.gnome.Calendar
          - org.gnome.Extensions
          - org.gnome.Weather

  - type: kargs
    kargs:
      - loglevel=4

  - type: justfiles
    validate: true

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
